name: Generate ZIP file

on: [pull_request]

jobs:
  generate-zip-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup node version and npm cache
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Node dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --no-optional

      - name: Generate ZIP file
        run: npm run package-plugin:deploy

      - name: Unzip generated archive
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq woocommerce-gutenberg-products-block.zip -d woocommerce-gutenberg-products-block

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: woocommerce-gutenberg-products-block
          path: woocommerce-gutenberg-products-block

      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: woocommerce-gutenberg-products-block
    
      # - name: Show artifact URL
      #   run: echo ${{ env.GITHUB_WORKSPACE }}/woocommerce-gutenberg-products-block.zip

      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: woocommerce-gutenberg-products-block.zip
      #     tag_name: ${{ github.ref_name }}
      #     body: ''
      #   env:
      #     repository: woocommerce/woocommerce-blocks-releases

      - name: Push release ZIP to woocommerce/woocommerce-blocks-releases
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.Woorelease  }}
        with:
          source_file: 'woocommerce-gutenberg-products-block.zip'
          destination_repo: 'woocommerce/woocommerce-blocks-releases'
          destination_folder: '/'
          user_email: 'info@nielslange.de'
          user_name: 'nielslange'
          commit_message: ${{ github.ref_name }}
