name: E2E tests

on:
    push:
        branches: [trunk]
    pull_request:

jobs:
    JSE2EWithGutenberg:
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5]
        name: JavaScript E2E Tests (WP latest with Gutenberg plugin)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/e2e-tests
              with:
                  WOOCOMMERCE_BLOCKS_PHASE: 3
                  GUTENBERG_EDITOR_CONTEXT: 'gutenberg'
                  WORDPRESS_VERSION: ''

    JSE2E:
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5]
        name: JavaScript E2E Tests (WP latest)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/e2e-tests
              with:
                  WOOCOMMERCE_BLOCKS_PHASE: 3
                  GUTENBERG_EDITOR_CONTEXT: ''
                  WORDPRESS_VERSION: ''

    JSE2EPrevious:
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5]
        name: JavaScript E2E Tests (WP 5.9)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/e2e-tests
              with:
                  WOOCOMMERCE_BLOCKS_PHASE: 3
                  GUTENBERG_EDITOR_CONTEXT: ''
                  WORDPRESS_VERSION: '5.9.0'

    JSE2EMinimiumWordPress:
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5]
        name: JavaScript E2E Tests (WP 5.8)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/e2e-tests
              with:
                  WOOCOMMERCE_BLOCKS_PHASE: 3
                  GUTENBERG_EDITOR_CONTEXT: ''
                  WORDPRESS_VERSION: '5.8.0'
