name: E2E tests

on:
    push:
        branches: [trunk]
    pull_request:

jobs:
    JSE2EWithGutenberg:
        strategy:
            fail-fast: false
            matrix:
                part: [1, 2, 3, 4, 5]
        name: JavaScript E2E Tests (WP latest with Gutenberg plugin)
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/e2e-tests
              with:
                  WOOCOMMERCE_BLOCKS_PHASE: '${{ secrets.GITHUB_TOKEN }}'
                  GUTENBERG_EDITOR_CONTEXT: '3'
                  WORDPRESS_VERSION: '1'
